### ISSUE TITLE
Implement Par System

### ISSUE THREAD

**Issue by Ozpyn** [darienyoder/software-engineering-team-beta#104]
The levels have an unused par variable, during the end screen, there should be a stat viewer of each level's strokes to par comparison. Maybe also even an overall par?

**Comment by Ozpyn** [comment]
I cannot for the life of me figure out how to draw the message between levels.

**Comment by clickyquack** [comment]
You should probably have the message show on screen for longer but otherwise it seems good

**Comment by clickyquack** [comment]
I just set it to two seconds myself. But, I noticed a bug; if you beat a level in level select, and then go back to level select from the main menu, the numbers are off. However, this is probably good enough to merge now and open a separate issue for this.
