### ISSUE TITLE
portals and velocity

### ISSUE THREAD

**Issue by Ozpyn** [darienyoder/software-engineering-team-beta#133]
when the ball travels through a portal, velocity should be maintained

**Comment by SageAndromeda** [comment]
When I was originally making them, I wanted them to kinda be like holes that can take the ball in and spit it out in another direction potentially with a varied amount of speed. 
For example, some minigolf courses will have multiple tubes next to each other; one gives a hole in one, one puts the ball close to the hole, and one puts it in a bad position. I think a better change would be to make it so we can pick the ball's outcome velocity when the hole is being set up.

**Comment by clickyquack** [comment]
A good fix would be extra variables for the tubes to have that correspond to the x and y value you want to have upon leaving the tube, such that you can choose the exact direction and speed that it leaves at (or, optionally, set it to zero)

**Comment by clickyquack** [comment]
> I think a better change would be to make it so we can pick the ball's outcome velocity when the hole is being set up.
Yeah, maybe have it so that the tubes obstacle has two extra variables corresponding to the x exit velocity and y exit velocity, preferably one that we can set directly in level data when specifying the tube.
