### ISSUE TITLE
Elevation: Visual & functional mismatch

### ISSUE THREAD

**Issue by clickyquack** [darienyoder/software-engineering-team-beta#172]
I was working on #167 and found out that it seems like the location of objects added through elevation do not match where it looks like they are visually. This only applies to the water and sand it seems. (See here: https://github.com/darienyoder/software-engineering-team-beta/tree/new-sand-%26-water. Currently the branch only places the objects in the right place visually, so these updated levels are a pretty good benchmark for testing whether they're functionally in the right place as well.) This should be fixed.

**Comment by darienyoder** [comment]
The issue was that rectangles had their values stored as strings for some reason, rather than numbers, so any checks to see if a point was inside the rectangle would return false. It has been fixed with 75782d1.
