### ISSUE TITLE
Level 9

### ISSUE THREAD

**Issue by SageAndromeda** [darienyoder/software-engineering-team-beta#184]
On level 9 (the rhombus one with the hills and water), the ball sometimes doesn't properly go into the water causing me to get stuck next to it and be unable to escape the pit

**Comment by SageAndromeda** [comment]
It generally seems to happen if the ball circles closely around the water instead of falling straight in

**Comment by clickyquack** [comment]
I think this is because it's treating it like it actually has an elevation of 843 if it doesn't actually overlap the water.

**Comment by clickyquack** [comment]
Fixed by using -843 for the water height instead: https://github.com/darienyoder/software-engineering-team-beta/tree/water-bug-fixed
