### ISSUE TITLE
Improved UI

### ISSUE THREAD

**Issue by darienyoder** [darienyoder/software-engineering-team-beta#186]
The UI is a little clunky, as it is using HTML buttons on top of the p5 canvas. We also have text on the screen that is always shown below the level objects. As unintuitive as it sounds, the easiest solution seems to be to add a third canvas for drawing UI elements.

**Comment by clickyquack** [comment]
I merged the pull request, but it's worth noting that this still needs the par system, trajectory color picker, and indication that the ball can be hit.
