### ISSUE TITLE
Camera work

### ISSUE THREAD

**Issue by adietz12** [darienyoder/software-engineering-team-beta#24]
Camera should always follow the ball. This will allow us to create bigger levels. Camera can zoom when the ball gets closer to hole. 
It's literally just camera.x, camera.y, camera.zoom

Reference material:
https://p5play.org/learn/camera.html?page=1

**Comment by darienyoder** [comment]
There's currently a fixed camera system that frames the entire level within the window. We could have separate modes for the camera to either follow the ball or show everything, decided by the level.

**Comment by Ozpyn** [comment]
Seems to be resolved as of [Pull 66](https://github.com/darienyoder/software-engineering-team-beta/pull/66)
