### ISSUE TITLE
Ball Trajectory

### ISSUE THREAD

**Issue by Ozpyn** [darienyoder/software-engineering-team-beta#26]
It should draw a little arrow so you know where the ball is going to go, like in real mini golf. This has a great example: https://editor.p5js.org/mtrc/sketches/Zc9cjBS3R

_Originally posted by @adietz12 in https://github.com/darienyoder/software-engineering-team-beta/issues/16#issuecomment-2350306414_
           
maybe it could also be simplistic, as in just a fading line

**Comment by Ozpyn** [comment]
This enhancement would pair nicely with this pullBack commit 4f7ab42

**Comment by Ozpyn** [comment]
trajectory implemented as of b909b2a, does spawn a coloring issue

**Comment by Ozpyn** [comment]
verification required

**Comment by adietz12** [comment]
Looks like the arrow is hidden when the ball is in sand + (any future object that's not the canvas). We can stop this bug now by setting the drawing order/yaer of the arrow to be the highest, since it's UI anyway.
