### ISSUE TITLE
Words with common endings

### ISSUE THREAD

**Issue by darienyoder** [darienyoder/software-engineering-team-beta#3]
Many of the unsolved words in [output.txt](https://github.com/darienyoder/software-engineering-team-beta/blob/main/wordle_assistant/output.txt) have common endings, which causes the program to guess the ending quickly, but get stuck guessing the letter it begins with. For example, here is the output for "water":
```
Word is water
1.  s   o  <r> [e]  s
2.  p  [a]  l  [e] [r]
3.  c  [a] [t] [e] [r]
4.  m  [a] [t] [e] [r]
5. <r> [a] [t] [e] [r]
6.  h  [a] [t] [e] [r]
```
It isn't necessarily the first letter that causes this problem. It is any letter in a word that can swapped with a different letter to create many possible new word. Here are some more examples:
```
Word is bakes
1. <s>  o   r  [e] [s]
2.  c  [a]  n  [e] [s]
3. [b] [a]  l  [e] [s]
4. [b] [a]  t  [e] [s]
5. [b] [a] <s> [e] [s]
6. [b] [a] <b> [e] [s]

Word is fixed
1.  s   o   r  [e]  s
2.  c   a   n  [e] [d]
3.  p  [i]  l  [e] [d]
4.  b  [i] <d> [e] [d]
5.  t  [i]  m  [e] [d]
6. <d> [i]  v  [e] [d]

Word is halls
1. <s>  o   r   e  [s]
2.  b  [a]  i   t  [s]
3.  c  [a] [l] [l] [s]
4.  p  [a] [l] [l] [s]
5.  f  [a] [l] [l] [s]
6.  m  [a] [l] [l] [s]
```

I believe we need to, in these situations, give up a guess simply to eliminate letters. For example, when the word is "halls", like above, after guessing "calls" and revealing the majority of the letters, the program could guess a word like "frump", as it would test the letters "p", "f", and"m" in just one guess instead of three.

**Comment by adietz12** [comment]
Since we don't need to worry about how fast it can solve the Wordle. I think we should just give up a turn or two to eliminate more common letters. 
Shit like:
Glyph

Jocks

Fixed

Brawn

**Comment by SageAndromeda** [comment]
What if we did something like when it has `>= 2 correct letters`, `2 <= used guesses < 5`, and `left guesses < possible words` then we do a guess using at least 3 unused letters.

For example: 
```
Word is bakes
1. <s>  o   r  [e] [s]
2.  c  [a]  n  [e] [s]    <--    >=2 correct letters, >=2 used guesses, more possible words than guesses left
3. [b]  i   g   h   t     <--    Only used unused letters. Leaves 4 guesses: BABES, BAKES, BALES, BASES
4. [b] [a] <s> [e] [s]    <-- Can be eliminated once we make it only acknowledge the one instance of s as correct.
5. [b] [a] <b> [e] [s]
6. [b] [a] [k] [e] [s]    <-- Final correct answer.
```

Do be careful coding the second guess that uses mostly unused letters. It risks freezing because it couldn't find valid words that meet the guess requirements.

An additional strategy to this would be finding two good words to use every time as our first and second guesses, then going from there. Ex: Adieu and Ghost gives 3 correct letters and 144 possible answers.

**Comment by clickyquack** [comment]
It would probably be ideal to orient the entire algorithm around choosing words that would eliminate as many possible words as possible as opposed to having each word try to be a potential guess.

**Comment by SageAndromeda** [comment]
We could count what unused letters are common in leftover words and try picking learn guesses that uses 2 or more. Example with guess 4 of `stake`:
```
1. [s]  o   r  <e> <s> 
2. <a>  p   p  <a>  l  
3. <t> <a> <t> <t>  y      <-- Possible words:  ['stage', 'stake', 'stave']. We haven't guessed k, g, or v. No word has all 3. Gecko uses 2.
4.  g  <e>  c  [k]  o  
5. [s] [t] [a] [k] [e] 
```
