### ISSUE TITLE
color issue

### ISSUE THREAD

**Issue by Ozpyn** [darienyoder/software-engineering-team-beta#31]
trajectory implemented as of b909b2a, does spawn a coloring issue

_Originally posted by @Ozpyn in https://github.com/darienyoder/software-engineering-team-beta/issues/26#issuecomment-2354388379_
            
when changing the stroke color, other colored elements are also changed

**Comment by vscicchi** [comment]
Did some testing on this. Changing the stroke weight parameter from 3 to 1 solves the issue, but having such a thin line to show the trajectory might not be the best. I'll try to find a better solution to this.

**Comment by vscicchi** [comment]
Worked on this bug some more. I managed to stop other colored elements from changing by using pushStyle() and popStyle(). However, this also caused the trajectory line to disappear for some reason. Gonna try more things, but I'm not exactly sure how to fix it.

**Comment by vscicchi** [comment]
I believe I got the trajectory line to work. Just committed a version where the trajectory line is thicker and red, and I believe it works without issue.
