### ISSUE TITLE
Multiple of the same letter

### ISSUE THREAD

**Issue by clickyquack** [darienyoder/software-engineering-team-beta#4]
In the actual Wordle game, if the final word has a given letter (e.g. s in chess), and you guess a word with more of the same letter than the word has (e.g. sassy), it will only highlight letters that are out of place as many times as they are in the word, and otherwise will show up as gray. (in the example, entering sassy when the word is chess would show /s-a-s+s-y). We currently don't check for this, leading to cases like this:
![image](https://github.com/user-attachments/assets/9305544c-b7e1-4619-bf1d-03325304a31d)
The third guess highlights t three times, when it should be only one. Same goes for the sixth guess showing multiple k's and a's. As such, we are not getting as much information from each guess as we would in an actual Wordle game.

**Comment by SageAndromeda** [comment]
Here's how I think we could eliminate this:

1. First check for green letters and note their placement.
2. Then check for yellow, but make sure to count the amount needed and what's in green already (ex: typing `sassy` for `chess` should give `<s> a s [s] y`. Note how the third s was already marked green so the first is yellow and the third is grey.
3. Finally, count remaining grey letters, but have some way to mark duplicates. We could do something like `s3` to indicate that there's already two `s` and remove anything with 3.

We also may just not want to add the third s to grey or yellow at all, though it does lose us some information. For example, if the word is `addle`, guessing `<d> <a> [d] d y` without adding the third `d` to grey still leaves a few guesses with 3 `d`'s such as `added`.

**Comment by SageAndromeda** [comment]
Penalizing _learn_ guesses with duplicate letters could work too. For example, `tatty` could have its score divided by 2 for the second `t`, then divided by 2 a second time because of the third. Learn guesses that reuse grey letters should also be penalized.
