### ISSUE TITLE
Tube entry

### ISSUE THREAD

**Issue by SageAndromeda** [darienyoder/software-engineering-team-beta#41]
The hole has the if statement `if (hole.overlaps(ball) &&ball.vel.x<=1.5 &&ball.vel.y<=1.5)` which stops the ball from entering if it's moving too fast. `tubeA` has almost the exact same if—`if (tubeA.overlaps(ball) &&ball.vel.x<=1.5 &&ball.vel.y<=1.5)`—but always lets the ball through.

**Comment by adietz12** [comment]
What is the bug?

**Comment by SageAndromeda** [comment]
@adietz12 It looks like the bug was only present in the Obstacles branch and not main. The issue I was having was that the ball should have ignored `TubeA` if it was going too fast, just like it does with the hole. But it wasn't doing that for some reason. It seems to be working fine in the main branch though so I don't really know what was going on
