### ISSUE TITLE
Pullback line on mouse

### ISSUE THREAD

**Issue by darienyoder** [darienyoder/software-engineering-team-beta#45]
When I pull back the mouse to make a shot, sometimes I lose track of where I started the pullback, making it hard to change where I'm aiming. The game should draw a line from the mouse to the point it started dragging to make it clear where your aim is anchored to.

**Comment by Ozpyn** [comment]
see: fe0fc08
added a simple userAssistance line

**Comment by darienyoder** [comment]
That's much better! My only note is that I think the line should only extend from the point where the mouse started dragging to the mouse's current position. Having it extend in the other direction feels a little disorienting.

**Comment by Ozpyn** [comment]
sorry, small maths issue; 8c53adc
fixed

**Comment by darienyoder** [comment]
Great, I think it's perfect.
