### ISSUE TITLE
Trajectory visibility

### ISSUE THREAD

**Issue by SageAndromeda** [darienyoder/software-engineering-team-beta#50]
There are 3 different parts to this:
1. There is a random grey line. I don't know where it came from, but it should probably be removed.
2. The red trajectory line is sometimes hidden behind obstacles. It needs to be on a higher layer. 
3. A red trajectory line will likely be very difficult to see against the green grass for someone who is red/green colorblind

**Comment by adietz12** [comment]
That random grey line is supposed to be the club apparently. @jeichmuller made it or something idk

**Comment by jeichmuller** [comment]
The grey line is not the club, its in the function drawUserAssistance() so I think its just there for visual help

**Comment by adietz12** [comment]
My bad I thought it was like the handle of the putter or something, I've only seen it connected to the rectangle.

**Comment by Ozpyn** [comment]
1. it is an artifact of allowing the user to start the pullBack from anywhere in the window
2. see [42](https://github.com/darienyoder/software-engineering-team-beta/issues/42)
3. see commit 30d1ae9

**Comment by Ozpyn** [comment]
For clarification on issue 1 : see [45](https://github.com/darienyoder/software-engineering-team-beta/issues/45)
