### ISSUE TITLE
Level Select Interface

### ISSUE THREAD

**Issue by darienyoder** [darienyoder/software-engineering-team-beta#59]
The user should be able to click a button on the main menu to go straight into a certain level, instead of always playing them in order.

**Comment by clickyquack** [comment]
I think I've mostly fixed it here: https://github.com/darienyoder/software-engineering-team-beta/tree/level-select
Once you beat a level from the level select screen it sends you back to the main menu. However, currently, if you try to go to level select again, selecting levels doesn't work. (If, however, you try to play the full game after playing a selected level, it does work.) I'm not sure why this is. This is probably good enough to commit to main and show in a Monday demo, and then just open a separate issue for this specific problem. Maybe? idk

**Comment by clickyquack** [comment]
Also I'm still kind of unsure how to implement tests for this at the moment.
