### ISSUE TITLE
Polygonal Obstacles

### ISSUE THREAD

**Issue by darienyoder** [darienyoder/software-engineering-team-beta#63]
Obstacles like the sandtrap and the water are currently rectangular, which is somewhat limiting to how we can place them in a level. There should be a way to make these types of obstacles use a polygon collider instead.

**Comment by darienyoder** [comment]
This may be covered in the elevation branch, if we set a certain arbitrary elevation to represent sand, water, and lava. That way, any complex shape could be represented using the terrain builder, without having to use sprites. It would also allow for visual effects like water ripples or sand particles, since the heightmap uses WebGL shaders.

**Comment by clickyquack** [comment]
> This may be covered in the elevation branch, if we set a certain arbitrary elevation to represent sand, water, and lava. That way, any complex shape could be represented using the terrain builder, without having to use sprites. It would also allow for visual effects like water ripples or sand particles, since the heightmap uses WebGL shaders.

So should I let you do this on your own, or wait for you to make enough progress in the elevation branch for me to be able to "piggyback" off of your work in it, or work on this independently of elevation entirely?

**Comment by darienyoder** [comment]
I'd say work on other issues for now, and by Monday I should have enough progress to show if the elevation solution will work or not. If I'm wrong, we can just continue as before, otherwise we can try piggybacking polygonal obstacles off the elevation branch.

**Comment by darienyoder** [comment]
This issue should be covered by #111
