### ISSUE TITLE
Up Arrow

### ISSUE THREAD

**Issue by SageAndromeda** [darienyoder/software-engineering-team-beta#7]
Professor DeLozier asked us to implement it so you can press the up arrow on the command line while the program is running to get the previous input. This needs to be implemented.

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by darienyoder** [comment]
The user can now begin their input with a caret symbol to build off of their previous input.
