### ISSUE TITLE
Ball Sprite Centering

### ISSUE THREAD

**Issue by SageAndromeda** [darienyoder/software-engineering-team-beta#75]
The image we use for the ball isn't centered so the ball's spinning makes it appear as if it's moving forwards and backwards. In the attached video, pay attention to how the ball overlaps the yellow line to its right.

https://github.com/user-attachments/assets/f6c80c98-d4f0-4d5f-a7f5-1902c7f0ec60

**Comment by Ozpyn** [comment]
See comments on commit: [71e25a6](https://github.com/darienyoder/software-engineering-team-beta/commit/71e25a63c0d39e519aa87349ff72479e907837db)
