### ISSUE TITLE
Trajectory

### ISSUE THREAD

**Issue by SageAndromeda** [darienyoder/software-engineering-team-beta#98]
Blue is now the default trajectory color in the Main branch, but this is still hard to see against the green. 
In my opinion, orange, yellow, purple, and black are the most visible. Changing it to a darker blue might also work well. 
The green trajectory is also super hard to see; if we're going to have one in that color, it should be significantly darker

**Comment by clickyquack** [comment]
Should we have a group vote or something

**Comment by SageAndromeda** [comment]
That would probably be a good idea. We could also ask our stakeholder

**Comment by Ozpyn** [comment]
Consider if you will: #102
